################################################################################
#
#  Github actions trigger (workflow script) for building Macaulay2
#
#    See https://help.github.com/en/actions for the documentation.
#
################################################################################

name: Build and Test Macaulay2

on:
  # trigger a test quick build at both PR (on dev)
  # and pushing to master (after merging or by Dan or Mike)
  push:
    branches:
      - master
      - development
      - global
      - release-1.16
  pull_request:
    branches:
      - master
      - development
  schedule:
    # cron time in UTC; set to 6a EDT
    - cron: '0 10 * * *'

defaults:
  run:
    working-directory: M2/BUILD/build

jobs:
  build:
    if: github.repository == 'Macaulay2/M2' || contains(github.ref, 'global')
    name: ${{ matrix.os }}-${{ matrix.build-system }}-${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # eventually make this true
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        build-system:
          - cmake
          - autotools
        compiler:
#          - clang10
          - gcc9
          - default
#          - xcode11
        # fine-tuning some configurations and excluding a few
        include:
          - compiler: gcc9
            cxx: g++-9
            cc: gcc-9
          - os: macos-latest
            build-system: cmake
            compiler: clang10
            cxx: clang++
            cc: clang
          - os: ubuntu-latest
            build-system: cmake
            compiler: clang10
            cxx: clang++-10
            cc: clang-10
        exclude:
          - os: macos-latest
            compiler: gcc9
#          - os: ubuntu-latest
#            compiler: xcode11

    steps:
      - uses: actions/checkout@v2

# ----------------------
#   Install missing tools and libraries for macOS
# ----------------------

      - name: Install requirements for macOS
        if: runner.os == 'macOS'
        run: |
          brew config
          # autoconf, libtool are already in the virtual env
          brew install automake ccache gnu-tar make ninja pkg-config yasm
          brew install bdw-gc boost cddlib eigen flint glpk libatomic_ops libomp mpfr mpir ncurses ntl tbb

# ----------------------
#   Install missing tools and libraries for Linux
# ----------------------

      - name: Install requirements for Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y -q --no-install-recommends clang-10 gfortran libtool-bin ninja-build yasm ccache
          sudo apt-get install -y -q --no-install-recommends libatomic-ops-dev libboost-stacktrace-dev \
                  libncurses-dev libncurses5-dev libreadline-dev libeigen3-dev liblapack-dev libxml2-dev \
                  libgc-dev libgdbm-dev libglpk-dev libgmp3-dev libgtest-dev libmpfr-dev libntl-dev gfan \
                  libcdd-dev libgivaro-dev libboost-regex-dev fflas-ffpack w3c-markup-validator
          # TODO: help autotools detect flint from brew
          brew install flint

# ----------------------
#   Steps common to all build variants
# ----------------------

      - name: Prepare build environment
        run: |
          echo "::set-env name=CC::${{ matrix.cc }}"
          echo "::set-env name=CXX::${{ matrix.cxx }}"
          echo "::set-env name=LD_LIBRARY_PATH::`brew --prefix`/lib:$LD_LIBRARY_PATH"

          if [[ "${{ runner.os }}" == "Linux" ]]; then
            PATH=/usr/lib/ccache:$PATH
            # Necessary for clang-10 on Linux
            # echo "::set-env name=LIBRARY_PATH::`llvm-config-10 --libdir`"
          else
            # PATH=`brew --prefix llvm`/bin:$PATH
            PATH=`brew --prefix ccache`/libexec:$PATH
            PATH=`brew --prefix make`/libexec/gnubin:$PATH
            # Necessary for clang on macOS
            # echo "::set-env name=LIBRARY_PATH::`llvm-config --libdir`"
          fi
          echo "::set-env name=PATH::$PATH"

      - uses: actions/cache@v2
        if: matrix.build-system == 'cmake' # TODO: remove when autotools is more efficient with space
        id: restore-cache
        with:
          path: |
            ~/.ccache
            ~/M2/BUILD/build/usr-host
          key: build-cache-${{ runner.os }}-${{ matrix.compiler }}-${{ matrix.build-system }}-${{ hashFiles('**/cmake/*-libraries.cmake') }}
          restore-keys: |
            build-cache-${{ runner.os }}-${{ matrix.compiler }}-${{ matrix.build-system }}-
            build-cache-${{ runner.os }}-${{ matrix.compiler }}-
            build-cache-${{ runner.os }}-


# ----------------------
#   Configure and build M2 using CMake
# ----------------------

      - name: Configure Macaulay2 using CMake
        if: matrix.build-system == 'cmake'
        run: |
          cmake -S../.. -B. -GNinja \
            -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_SYSTEM_PREFIX_PATH=`brew --prefix` \
            -DBUILD_NATIVE=OFF -DBUILD_LIBRARIES="Givaro;FFLAS_FFPACK" # TODO: remove when the packages are updated

      - name: Build libraries using Ninja
        if: matrix.build-system == 'cmake' # && steps.restore-cache.outputs.cache-hit != 'true'
        run: |
          cmake --build . --target build-libraries build-programs

      - name: Build Macaulay2 using Ninja
        if: matrix.build-system == 'cmake'
        run: |
          cmake --build . --target M2-core install-packages

# ----------------------
#   Configure and build M2 using Autotools
# ----------------------

      - name: Configure Macaulay2 using Autotools
        if: matrix.build-system == 'autotools'
        run: |
          make -C ../.. get-libtool get-automake get-autoconf
          make -C ../.. all
          ../../configure --enable-download

      - name: Build Macaulay2 using Make
        if: matrix.build-system == 'autotools'
        run: |
          make

# ----------------------
#   Run tests
# ----------------------

      - name: Run Tests using CTest
        if: matrix.build-system == 'cmake' && matrix.os == 'ubuntu-latest'
        run: |
          # cmake --build . --target M2-unit-tests
          # ctest -R "unit-tests"
          ctest -R "normal/" -E "command|program|schenck|threads|doc-links" -j4 --output-on-failure

      - name: Run Tests using Autotools
        if: matrix.build-system == 'autotools' && matrix.os == 'ubuntu-latest'
        run: |
          make check
          make -C Macaulay2/html-check-links check
          make validate-html

# ----------------------
#   Upload build logs
# ----------------------

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
           name: ${{ matrix.os }}-${{ matrix.build-system }}-${{ matrix.compiler }}-logs
           path: |
             # Autotools
             M2/BUILD/build/config.log
             M2/BUILD/build/libraries/*/build/*/config.log
             # CMake
             M2/BUILD/build/CMakeFiles/CMakeCache.txt
             M2/BUILD/build/CMakeFiles/CMake(Error|Output).log
             M2/BUILD/build/libraries/*/build/config.log
             # Example errors
             M2/BUILD/build/usr-dist/common/share/doc/Macaulay2/*/example-output/*.errors
